-- Regression checks for migration 022 (server-only RLS boundary).
-- Run via db/tests/run.sh against a disposable PostgreSQL database.
\set ON_ERROR_STOP on

begin;

-- Verify that future tables created by the migration owner do not inherit
-- Supabase-style broad browser grants. The test table is rolled back below.
create table public.__nasrinai_security_probe (
  id bigint generated by default as identity primary key
);
alter table public.__nasrinai_security_probe enable row level security;

do $$
declare
  r record;
  v_role text;
  v_privilege text;
begin
  for r in
    select c.oid, n.nspname, c.relname, c.relkind, c.relrowsecurity
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public'
       and c.relkind in ('r', 'p', 'v', 'm', 'f')
  loop
    if r.relkind in ('r', 'p') and not r.relrowsecurity then
      raise exception 'RLS is disabled on public relation %.%', r.nspname, r.relname;
    end if;

    foreach v_role in array array['anon', 'authenticated']::text[] loop
      foreach v_privilege in array array[
        'SELECT', 'INSERT', 'UPDATE', 'DELETE',
        'TRUNCATE', 'REFERENCES', 'TRIGGER'
      ]::text[] loop
        if has_table_privilege(v_role, r.oid, v_privilege) then
          raise exception 'browser role % has % on public relation %.%',
            v_role, v_privilege, r.nspname, r.relname;
        end if;
      end loop;
    end loop;
  end loop;

  for r in
    select c.oid, n.nspname, c.relname
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public'
       and c.relkind = 'S'
  loop
    foreach v_role in array array['anon', 'authenticated']::text[] loop
      foreach v_privilege in array array['USAGE', 'SELECT', 'UPDATE']::text[] loop
        if has_sequence_privilege(v_role, r.oid, v_privilege) then
          raise exception 'browser role % has % on public sequence %.%',
            v_role, v_privilege, r.nspname, r.relname;
        end if;
      end loop;
    end loop;
  end loop;
end
$$;

rollback;

\echo 'RLS security boundary checks passed'
